<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcaInformationService.Shared\EcaInformationSystem.Shared.csproj" />
    <ProjectReference Include="..\EcaInformationSystem.Domain\EcaInformationSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Behaviours\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="DTOs\BeneficiarySummaryResultDto.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="itext7" Version="9.6.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.6.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.6" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>

</Project>
