<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <!-- ✅ Add these two for .NET 10 -->
	  <PublishTrimmed>false</PublishTrimmed>
	  <RunAOTCompilation>false</RunAOTCompilation>
	  <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
	  <PublishIISAssets>true</PublishIISAssets>
	  <!-- ✅ ADD THIS — forces generation of blazor.webassembly.js -->
	  <WasmFingerprintAssets>false</WasmFingerprintAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Havit.Blazor.Components.Web.Bootstrap" Version="4.24.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcaInformationService.Shared\EcaInformationSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\BeneficiaryInformation\LiquidationComponents\Modal\" />
  </ItemGroup>

</Project>
