// <auto-generated />
using System;
using EcaInformationSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcaInformationSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706081306_AddUserLastSeenAt")]
    partial class AddUserLastSeenAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.Barangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsgcCodeBarangay")
                        .HasColumnType("int");

                    b.Property<int>("PsgcCodeMunicipality")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PsgcCodeBarangay")
                        .IsUnique()
                        .HasDatabaseName("UQ_Barangay_PsgcCode");

                    b.ToTable("Barangays");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.BeneficiaryDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeneficiaryInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("OriginalFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryInformationId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("BeneficiaryDocuments");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.BeneficiaryFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeneficiaryInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FindingRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FindingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryInformationId")
                        .IsUnique();

                    b.HasIndex("FindingStatus");

                    b.ToTable("BeneficiaryFindings");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.BeneficiaryInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssessmentRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Barangay")
                        .HasColumnType("int");

                    b.Property<string>("Batch")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BatchCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Citizenship")
                        .HasColumnType("int");

                    b.Property<int?>("CivilStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CoDateApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CoDateEndorsed")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CoStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEndorsed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("EligibilityRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndigenousPeople")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonWithDisability")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ModeOfPayment")
                        .HasColumnType("int");

                    b.Property<int>("Municipality")
                        .HasColumnType("int");

                    b.Property<int?>("NcscRrn")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OscaIdDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("OscaIdNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("PayrollQuarter")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Province")
                        .HasColumnType("int");

                    b.Property<int?>("Quarter")
                        .HasColumnType("int");

                    b.Property<string>("RefCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefYear")
                        .HasColumnType("int");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<int?>("RemarkCategory")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Validator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "CoStatus")
                        .HasDatabaseName("IX_Beneficiary_CoStatus");

                    b.HasIndex("IsDeleted", "IsCompliant")
                        .HasDatabaseName("IX_Beneficiary_IsCompliant");

                    b.HasIndex("IsDeleted", "IsEligible")
                        .HasDatabaseName("IX_Beneficiary_IsEligible");

                    b.HasIndex("IsDeleted", "PaymentStatus")
                        .HasDatabaseName("IX_Beneficiary_PaymentStatus");

                    b.HasIndex("IsDeleted", "CoStatus", "IsCompliant")
                        .HasDatabaseName("IX_Beneficiary_CoStatus_Compliant");

                    b.HasIndex("IsDeleted", "CoStatus", "IsEligible")
                        .HasDatabaseName("IX_Beneficiary_CoStatus_Eligible");

                    b.HasIndex("IsDeleted", "BirthDate", "LastName", "FirstName")
                        .HasDatabaseName("IX_Beneficiary_BirthDate_NameSort");

                    b.HasIndex("IsDeleted", "LastName", "FirstName", "MiddleName")
                        .HasDatabaseName("IX_Beneficiary_NameSort_Default");

                    b.HasIndex("IsDeleted", "Quarter", "Batch", "RefYear")
                        .HasDatabaseName("IX_Beneficiary_RefNumber");

                    b.HasIndex("IsDeleted", "Barangay", "LastName", "FirstName", "MiddleName")
                        .HasDatabaseName("IX_Beneficiary_Barangay_NameSort");

                    b.HasIndex("IsDeleted", "BatchCode", "LastName", "FirstName", "MiddleName")
                        .HasDatabaseName("IX_Beneficiary_BatchCode_NameSort");

                    b.HasIndex("IsDeleted", "Municipality", "LastName", "FirstName", "MiddleName")
                        .HasDatabaseName("IX_Beneficiary_Municipality_NameSort");

                    b.HasIndex("IsDeleted", "Province", "LastName", "FirstName", "MiddleName")
                        .HasDatabaseName("IX_Beneficiary_Province_NameSort");

                    b.HasIndex("LastName", "FirstName", "MiddleName", "BirthDate", "OscaIdNumber", "NcscRrn")
                        .HasDatabaseName("IX_Beneficiary_DuplicateDetection");

                    b.ToTable("BeneficiaryInformations");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("ThumbnailData")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId")
                        .IsUnique()
                        .HasFilter("[ChatMessageId] IS NOT NULL");

                    b.ToTable("ChatAttachments");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEveryoneMention")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MentionedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId")
                        .HasDatabaseName("IX_ChatMention_ChatMessageId");

                    b.HasIndex("MentionedUserId")
                        .HasDatabaseName("IX_ChatMention_MentionedUserId");

                    b.ToTable("ChatMentions");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEveryoneMention")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToMessageId")
                        .HasDatabaseName("IX_ChatMessage_ReplyToMessageId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_ChatMessage_SenderId");

                    b.HasIndex("RoomId", "SentAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ChatMessage_Room_SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMessageReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId")
                        .HasDatabaseName("IX_ChatMessageReaction_ChatMessageId");

                    b.HasIndex("ChatMessageId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ChatMessageReaction_MessageUser");

                    b.ToTable("ChatMessageReactions");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatReadStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ChatReadStatus_RoomUser");

                    b.ToTable("ChatReadStatuses");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RegionCode")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique()
                        .HasDatabaseName("UQ_ChatRoom_SingleGlobalRoom")
                        .HasFilter("[Type] = 2");

                    b.HasIndex("Type", "RegionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_ChatRoom_OneRoomPerRegion")
                        .HasFilter("[Type] = 1");

                    b.ToTable("ChatRooms");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatRoomMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ChatRoomMember_UserId");

                    b.HasIndex("RoomId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ChatRoomMember_RoomUser");

                    b.ToTable("ChatRoomMembers");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BeneficiaryInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryInformationId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("BeneficiaryInformationId", "CreatedAt");

                    b.HasIndex("UserName", "CreatedAt");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsgcCodeMunicipality")
                        .HasColumnType("int");

                    b.Property<int>("PsgcCodeProvince")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PsgcCodeMunicipality")
                        .IsUnique()
                        .HasDatabaseName("UQ_Municipality_PsgcCode");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.PdoJurisdiction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PsgcCodeMunicipality")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PsgcCodeMunicipality");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PsgcCodeMunicipality")
                        .IsUnique();

                    b.ToTable("PdoJurisdictions");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.PendingUserRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Region")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Viewer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("PendingUserRegistrations", (string)null);
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsgcCodeProvince")
                        .HasColumnType("int");

                    b.Property<int>("PsgcCodeRegion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PsgcCodeProvince")
                        .IsUnique()
                        .HasDatabaseName("UQ_Province_PsgcCode");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsgcCodeRegion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PsgcCodeRegion")
                        .IsUnique()
                        .HasDatabaseName("UQ_Region_PsgcCode");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.BeneficiaryDocument", b =>
                {
                    b.HasOne("EcaInformationSystem.Domain.Entities.BeneficiaryInformation", "BeneficiaryInformation")
                        .WithMany()
                        .HasForeignKey("BeneficiaryInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeneficiaryInformation");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.BeneficiaryFinding", b =>
                {
                    b.HasOne("EcaInformationSystem.Domain.Entities.BeneficiaryInformation", "BeneficiaryInformation")
                        .WithOne("Finding")
                        .HasForeignKey("EcaInformationSystem.Domain.Entities.BeneficiaryFinding", "BeneficiaryInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeneficiaryInformation");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatAttachment", b =>
                {
                    b.HasOne("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMessage", "Message")
                        .WithOne("Attachment")
                        .HasForeignKey("EcaInformationSystem.Domain.Entities.ChatEntities.ChatAttachment", "ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Message");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMention", b =>
                {
                    b.HasOne("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMessage", "Message")
                        .WithMany("Mentions")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMessage", b =>
                {
                    b.HasOne("EcaInformationSystem.Domain.Entities.ChatEntities.ChatRoom", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMessageReaction", b =>
                {
                    b.HasOne("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMessage", "Message")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatRoomMember", b =>
                {
                    b.HasOne("EcaInformationSystem.Domain.Entities.ChatEntities.ChatRoom", "Room")
                        .WithMany("Members")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.PdoJurisdiction", b =>
                {
                    b.HasOne("EcaInformationSystem.Domain.Entities.PendingUserRegistration", "User")
                        .WithMany("Jurisdictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.BeneficiaryInformation", b =>
                {
                    b.Navigation("Finding");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatMessage", b =>
                {
                    b.Navigation("Attachment");

                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.ChatEntities.ChatRoom", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("EcaInformationSystem.Domain.Entities.PendingUserRegistration", b =>
                {
                    b.Navigation("Jurisdictions");
                });
#pragma warning restore 612, 618
        }
    }
}
